### ISSUE TITLE
Module does not support 'android' platform

### ISSUE THREAD

**Issue by chrisburnette01** [realtime-framework/RealtimeMessaging-Appcelerator#1]
The module does not support 'android' platform for Titanium SDK 6.0.x.

**Comment by realtime-framework** [comment]
Can you send us the build error log?

**Comment by chrisburnette01** [comment]
This is not build issue, that says after I installed this module into my titanium project that using Titanium SDK '6.x.x'..
Looks like iOS module working well. but thats only says for 'android' platform.

finally I tried to use lower titanium sdk version(5.x.x) instead of 6.x.x. then this issue has resolve. once I didn't compile the app yet.
